version: "3.9"
services:
  web:
    image: jmixtest/jmix-pm:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - postgres
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: tm04122023
      POSTGRES_USER: jmix
      POSTGRES_PASSWORD: jmix